// frontend/src/components/reports/CampReportGenerator.jsx
import React, { useState } from 'react';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { DownloadIcon } from '@heroicons/react/outline';

const CampReportGenerator = ({ campId, onGenerate }) => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const generatePDF = async () => {
    setLoading(true);
    setError('');

    try {
      // Fetch detailed report data
      const response = await fetch(`${import.meta.env.VITE_BACKEND_URL}/api/camps/${campId}/report`);
      const result = await response.json();

      if (!response.ok) {
        throw new Error(result.message || 'Failed to fetch report data');
      }

      const reportData = result.data;

      // Create PDF
      const doc = new jsPDF();

      // Add title
      doc.setFontSize(20);
      doc.text('Blood Camp Report', 20, 20);
      doc.setFontSize(12);
      doc.text(`Report Generated: ${new Date().toLocaleDateString()}`, 20, 30);

      // Camp Information
      doc.setFontSize(14);
      doc.text('Camp Information', 20, 45);
      doc.setFontSize(10);
      doc.text(`Title: ${reportData.camp.title}`, 20, 55);
      doc.text(`Date: ${new Date(reportData.camp.date).toLocaleDateString()}`, 20, 60);
      doc.text(`Location: ${reportData.camp.location.venue}, ${reportData.camp.location.city}`, 20, 65);
      doc.text(`Organizer: ${reportData.hospital.name}`, 20, 70);

      // Statistics Section
      let yPos = 85;
      doc.setFontSize(14);
      doc.text('Statistics', 20, yPos);
      doc.setFontSize(10);
      yPos += 10;
      doc.text(`Total Registrations: ${reportData.statistics.totalRegistrations}`, 20, yPos);
      yPos += 5;
      doc.text(`Total Check-ins: ${reportData.statistics.totalCheckIns}`, 20, yPos);
      yPos += 5;
      doc.text(`Total Donations: ${reportData.statistics.totalDonations}`, 20, yPos);
      yPos += 5;
      doc.text(`Total Units Collected: ${reportData.statistics.totalUnitsCollected}`, 20, yPos);
      yPos += 5;
      doc.text(`Goal Achievement: ${reportData.statistics.percentageAchieved}%`, 20, yPos);

      // Blood Type Distribution Table
      yPos += 15;
      doc.setFontSize(14);
      doc.text('Blood Type Distribution', 20, yPos);
      
      const bloodTypeRows = Object.entries(reportData.bloodTypeDistribution).map(([type, data]) => [
        type,
        data.count.toString(),
        data.units.toString()
      ]);

      doc.autoTable({
        startY: yPos + 5,
        head: [['Blood Type', 'Donors', 'Units']],
        body: bloodTypeRows,
        theme: 'striped',
        styles: { fontSize: 10 },
        headStyles: { fillColor: [22, 163, 74] }
      });

      // Donor List Table
      const tableY = doc.lastAutoTable.finalY + 15;
      doc.setFontSize(14);
      doc.text('Donor List', 20, tableY);

      const donorRows = reportData.donorList.map(donor => [
        donor.name,
        donor.bloodGroup,
        donor.checkInTime ? new Date(donor.checkInTime).toLocaleTimeString() : '-',
        donor.unitsDonated.toString()
      ]);

      doc.autoTable({
        startY: tableY + 5,
        head: [['Name', 'Blood Group', 'Check-in Time', 'Units Donated']],
        body: donorRows,
        theme: 'striped',
        styles: { fontSize: 9 },
        headStyles: { fillColor: [37, 99, 235] }
      });

      // Footer
      const footerY = doc.lastAutoTable.finalY + 20;
      doc.setFontSize(8);
      doc.text('Generated by Khoonn Blood Bank Management System', 20, footerY);
      doc.text('For official use only. Requires hospital administrator approval.', 20, footerY + 5);

      // Signature area
      doc.setFontSize(10);
      const signatureY = doc.internal.pageSize.height - 40;
      doc.text('Staff Signature: ________________________', 20, signatureY);
      doc.text('Admin Approval: ________________________', 120, signatureY);

      // Save the PDF
      const fileName = `BloodCamp_Report_${reportData.camp.title.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;
      doc.save(fileName);

      if (onGenerate) onGenerate();
      
    } catch (err) {
      console.error('Error generating PDF:', err);
      setError(err.message || 'Failed to generate report');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="mb-4">
      <button
        onClick={generatePDF}
        disabled={loading}
        className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
      >
        {loading ? (
          <>
            <svg className="animate-spin h-4 w-4 text-white" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
            Generating Report...
          </>
        ) : (
          <>
            <DownloadIcon className="w-4 h-4" />
            Export Report (PDF)
          </>
        )}
      </button>
      
      {error && (
        <div className="mt-2 p-3 bg-red-50 text-red-800 rounded-lg text-sm">
          Error: {error}
        </div>
      )}
    </div>
  );
};

export default CampReportGenerator;